### ISSUE TITLE
Step 4 fails because Redux appears to be missing.

### ISSUE THREAD

**Issue by dknesek** [sflahave/ngHmr#1]
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ng2-redux' in '/Users/doug/ngHmr/src/app'
 @ ./src/app/app.module.ts 15:18-38
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi app

ERROR in ./src/app/counter/counter.list.component.ts
Module not found: Error: Can't resolve 'ng2-redux' in '/Users/doug/ngHmr/src/app/counter'
 @ ./src/app/counter/counter.list.component.ts 13:18-38
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi app

ERROR in ./src/app/store/counter.actions.ts
Module not found: Error: Can't resolve 'ng2-redux' in '/Users/doug/ngHmr/src/app/store'
 @ ./src/app/store/counter.actions.ts 12:18-38
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi app

ERROR in ./src/app/store/state.helpers.ts
Module not found: Error: Can't resolve 'redux-logger' in '/Users/doug/ngHmr/src/app/store'
 @ ./src/app/store/state.helpers.ts 3:19-42
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi app

ERROR in [at-loader] src/app/app.module.ts:5:59 
    Cannot find module 'ng2-redux'.

ERROR in [at-loader] src/app/counter/counter.list.component.ts:4:24 
    Cannot find module 'ng2-redux'.

ERROR in [at-loader] src/app/store/counter.actions.ts:3:25 
    Cannot find module 'ng2-redux'.

**Comment by sflahave** [comment]
Hey @dknesek  - sorry, I just noticed this now. Did you get this figured out? I'm guessing you didn't run `npm install`  (or `yarn`) after checking out the `step4` branch.
